# Set to message you want to be sent when a player attempts to elytra boost without permission.
# Uses standard color codes. https://www.digminecraft.com/lists/color_list_pc.php

# If you make message empty quotes, it won't send anything.

message: "&4&lYou cannot boost your elytra with fireworks!"

# List of worlds to explicitly allow/disallow flying with eltrya in.
world-list: []

# World list type. "Whitelist" to only allow those worlds to be flown in,
# Blacklist to specifically disallow it in that specific world, or Disabled to disable
# the world list functionality.
world-list-type: "Disabled"